# Generated by Django 3.1.8 on 2021-06-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='number',
        ),
    ]
