# Generated by Django 3.1.8 on 2021-06-06 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_remove_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.AddField(
            model_name='card',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='flashcard',
            field=models.ManyToManyField(blank=True, null=True, to='flashcard.FlashCard'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcard.card'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
