# Generated by Django 3.1.8 on 2021-06-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_auto_20210606_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='number',
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
